### 회원가입 (안성모)
POST http://localhost:8080/members
Content-Type: application/json

{
  "email": "asm0619_1@naver.com",
  "password": "123123123",
  "nickname": "안성모_1"
}

### 글 작성 (안성모)
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "성모_1글 제목1",
  "content": "성모_1글 본문1",
  "memberId": 3
}

### 글 작성 (테스트맨1)
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "테스트맨1글 제목1",
  "content": "테스트맨1글 본문1",
  "memberId": 2
}

### 글 작성 (없는 작성자)
POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "성모글 제목",
  "content": "성모글 본문",
  "memberId": 10
}

### 글 수정 (성모_1)
PATCH http://localhost:8080/posts/4
Content-Type: application/json

{
  "title": "성모_1글 제목1 수정1",
  "content": "성모_1글 본문1 수정1"
}

### 게시글 전체 조회 (처음 20개)
GET http://localhost:8080/posts

### 게시글 전체 조회 (다음 20개)
GET http://localhost:8080/posts?size=100

### 오류
GET http://localhost:8080/posts?cursor=abd

### 마지막 조회
GET http://localhost:8080/posts?cursor=2024-11-09T16:13:54_1006381

### 댓글 있는 게시글 삭제 (1번 글 - comment-api.http에서 댓글 단 글)
DELETE http://localhost:8080/posts/6

### 삭제 후 전체 조회 (실제로 뭐가 지워졌는지 확인)
GET http://localhost:8080/posts

###
GET http://localhost:8080/posts?cursor=2024-11-09T16:31:54_1006363